Update Dockerfile.redhat

diff --git a/Dockerfile.redhat b/Dockerfile.redhat
--- a/Dockerfile.redhat
+++ b/Dockerfile.redhat
@@ -1,6 +1,5 @@
-#
+##
 # Copyright (c) 2020-2023 Intel Corporation
-#
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
@@ -12,23 +11,22 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-#
 
-ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.5
+ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
 ARG BUILD_IMAGE=build
 ARG PKG_IMAGE=pkg
-ARG RELEASE_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:9.5
+ARG RELEASE_BASE_IMAGE=registry.access.redhat.com/ubi9-minimal:9.6
 
 FROM $BASE_IMAGE as base_build
-ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.5
+ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
 
 SHELL ["/bin/bash", "-xo", "pipefail", "-c"]
 
-ARG JOBS=8
-ARG VERBOSE_LOGS=OFF
-ARG LTO_ENABLE=OFF
-ARG LTO_CXX_FLAGS=""
-ARG LTO_LD_FLAGS="-Wl,-z,relro"
+ARG JOBS=16
+ARG VERBOSE_LOGS=ON
+ARG LTO_ENABLE=ON
+ARG LTO_CXX_FLAGS="-flto=auto -ffat-lto-objects -march=haswell"
+ARG LTO_LD_FLAGS="-flto=auto -ffat-lto-objects"
 
 # hadolint ignore=DL3041
 RUN echo -e "max_parallel_downloads=8\nretries=50" >> /etc/dnf/dnf.conf && \
@@ -101,13 +99,13 @@ RUN if [ "$VERBOSE_LOGS" == "ON" ] ; then export VERBOSE=1 ; fi && ./install_ope
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
 FROM base_build as build
-ARG BASE_IMAGE
+ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
 
 SHELL ["/bin/bash", "-xo", "pipefail", "-c"]
 
-ARG JOBS=40
-ARG VERBOSE_LOGS=OFF
-ARG LTO_ENABLE=OFF
+ARG JOBS=16
+ARG VERBOSE_LOGS=ON
+ARG LTO_ENABLE=ON
 
 # hadolint ignore=DL3041
 RUN dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/opencl-headers-3.0-6.20201007gitd65bcc5.el9.noarch.rpm && \
@@ -123,7 +121,7 @@ RUN dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os
             unzip \
             vim \
             xz \
-            python3-devel \ 
+            python3-devel \
             libicu-devel && \
             dnf clean all
 
@@ -157,15 +155,15 @@ RUN  dnf install -y https://github.com/linux-test-project/lcov/releases/download
 
 ENV TF_SYSTEM_LIBS="curl"
 ENV TEST_LOG="/root/.cache/bazel/_bazel_root/bc57d4817a53cab8c785464da57d1983/execroot/ovms/bazel-out/test.log"
-ARG ov_source_branch=master
-ARG ov_contrib_branch=master
-ARG ov_source_org=openvinotoolkit
-ARG ov_contrib_org=openvinotoolkit
+ARG ov_source_branch=releases/2025/1
+ARG ov_contrib_branch=releases/2025/1
+ARG ov_source_org=opendatahub-io
+ARG ov_contrib_org=opendatahub-io
 ARG ov_use_binary=0
 ARG DLDT_PACKAGE_URL
 ARG TEMP_DIR=/tmp/openvino_installer
 ARG CMAKE_BUILD_TYPE=Release
-ARG debug_bazel_flags="--strip=always  --config=mp_on_py_on --//:distro=redhat"
+ARG debug_bazel_flags="--strip=always --define MEDIAPIPE_DISABLE=0 --define PYTHON_DISABLE=0 --config=mp_on_py_on --verbose_failures --//:distro=redhat --local_ram_resources=23552 --local_cpu_resources=16"
 
 ################### BUILD OPENVINO FROM SOURCE - buildarg ov_use_binary=0  ############################
 # hadolint ignore=DL3041
@@ -222,7 +220,7 @@ RUN if [ -f /opt/intel/openvino/samples/cpp/build_samples.sh ];  then /opt/intel
 ENV OpenVINO_DIR=/opt/intel/openvino/runtime/cmake
 ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/intel/openvino/runtime/lib/intel64/:/opt/opencv/lib/:/opt/intel/openvino/runtime/3rdparty/tbb/lib/
 
-ARG ov_tokenizers_branch=master
+ARG ov_tokenizers_branch=releases/2025/1
 # hadolint ignore=DL3003
 RUN git clone https://github.com/openvinotoolkit/openvino_tokenizers.git /openvino_tokenizers && cd /openvino_tokenizers && git checkout $ov_tokenizers_branch && git submodule update --init --recursive
 WORKDIR /openvino_tokenizers/build
@@ -281,7 +279,7 @@ ENV PYTHONPATH=/opt/intel/openvino/python:/ovms/bazel-bin/src/python/binding
 
 WORKDIR /ovms
 
-ARG PROJECT_VERSION="2025.1"
+ARG PROJECT_VERSION="2025.1.0"
 LABEL description="OpenVINO Model Server"
 ARG minitrace_flags
 
@@ -323,26 +321,49 @@ RUN python3 -c "import json; m={'PROJECT_VERSION':'${PROJECT_VERSION}','OPENVINO
 
 FROM $BUILD_IMAGE as capi-build
 # C api shared library
-ARG CAPI_FLAGS="--strip=always  --config=mp_off_py_off --//:distro=redhat"
-ARG JOBS=40
-RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:ovms_shared
+ARG CAPI_FLAGS="--strip=always --config=mp_off_py_off --verbose_failures --//:distro=redhat --local_ram_resources=23552 --local_cpu_resources=16 --subcommands"
+ARG JOBS=16
+
+#RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:ovms_shared
+
+RUN mkdir -p /tmp/bazel-output && \
+    bazel --output_base=/tmp/bazel-output \
+          build //src:ovms_shared && \
+    find /tmp/bazel-output -name libovms_shared.so && \
+    LIB_PATH=$(find /tmp/bazel-output -name libovms_shared.so | head -n1) && \
+    echo "Found built file: $LIB_PATH" && \
+    mkdir -p /ovms_release/lib && \
+    cp -v "$LIB_PATH" /ovms_release/lib/
+
 
 # C api app with bazel
 # hadolint ignore=DL3059
 RUN bazel build --jobs $JOBS ${CAPI_FLAGS} //src:capi_cpp_example
 
 # C-API benchmark app
-RUN bazel build --jobs=$JOBS ${CAPI_FLAGS} //src:capi_benchmark && ./bazel-bin/src/capi_benchmark --niter 2 --nstreams 1 --servable_name "dummy"
-# C-api C/C++ app with gcc
-COPY MakefileCapi /ovms/
-RUN make -f MakefileCapi cpp CAPI_FLAGS="${CAPI_FLAGS}" && \
-    make -f MakefileCapi c CAPI_FLAGS="${CAPI_FLAGS}"
+RUN bazel build --jobs=$JOBS ${CAPI_FLAGS} //src:capi_benchmark
+
+#workaround for debugging
+#RUN find /root/.cache/bazel/ -type f -name '*capi_benchmark*'
+
+#RUN ls -al /ovms_release/lib/
+
+RUN pwd && ls -al
+
+RUN bazel build --jobs=$JOBS ${CAPI_FLAGS} //src:capi_benchmark && \
+    echo "WORKDIR at build-time: $PWD" && \
+    bazel info bazel-bin && \
+    find $(bazel info bazel-bin)/src -type f -name capi_benchmark
 
 RUN mkdir -p /ovms_release/lib/ ; find /ovms/bazel-out/k8-*/bin -iname 'libovms_shared.so'  -exec cp -v {} /ovms_release/lib/ \;
+#RUN mkdir -p /ovms_release/lib/ ; find $(bazel info bazel-bin) -iname 'libovms_shared.so' -exec cp -v {} /ovms_release/lib/ \;
+
+#debuggig to find the correct lib file
+
 
 FROM $BUILD_IMAGE as pkg
 
-RUN mkdir /patchelf 
+RUN mkdir /patchelf
 WORKDIR /patchelf
 # hadolint ignore=DL3003
 RUN wget -q https://github.com/NixOS/patchelf/archive/0.10.tar.gz && \
@@ -353,7 +374,11 @@ WORKDIR /
 ARG BASE_OS=redhat
 ARG ov_use_binary=0
 ARG FUZZER_BUILD=0
-ARG debug_bazel_flags="--strip=always  --config=mp_on_py_on --//:distro=redhat"
+ARG debug_bazel_flags="--strip=always --define MEDIAPIPE_DISABLE=0 --define PYTHON_DISABLE=0 --config=mp_on_py_on --verbose_failures --//:distro=redhat --local_ram_resources=23552 --local_cpu_resources=16"
+
+#workaround to debug
+RUN find / -name libovms_shared.so 2>/dev/null || echo "Not found"
+
 COPY --from=capi-build /ovms_release/lib/libovms_shared.so /ovms_release/lib/
 COPY create_package.sh /
 RUN ./create_package.sh ; if ! [[ $debug_bazel_flags == *"_py_off"* ]]; then \
@@ -378,11 +403,11 @@ LABEL "description"="OpenVINO(TM) Model Server is a solution for serving AI mode
 LABEL "maintainer"="dariusz.trawinski@intel.com"
 ARG INSTALL_RPMS_FROM_URL=
 ARG INSTALL_DRIVER_VERSION="23.22.26516"
-ARG GPU=0
-ARG debug_bazel_flags=
+ARG GPU=1
+ARG debug_bazel_flags="--strip=always --define MEDIAPIPE_DISABLE=0 --define PYTHON_DISABLE=0 --config=mp_on_py_on --verbose_failures --//:distro=redhat --local_ram_resources=23552 --local_cpu_resources=16"
 LABEL bazel-build-flags=${debug_bazel_flags}
 LABEL supported-devices="CPU=1 GPU=${GPU}"
-ARG RELEASE_BASE_IMAGE
+ARG RELEASE_BASE_IMAGE=registry.access.redhat.com/ubi9-minimal:9.6
 LABEL base-image=${RELEASE_BASE_IMAGE}
 
 ENV PYTHONPATH=/ovms/lib/python:/ovms/python_deps
